import os

SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE_URL")
SQLALCHEMY_TRACK_MODIFICATIONS = False

SECRET_KEY = os.getenv("SECRET_KEY")

UPLOAD_FOLDER = 'uploads'
MAX_CONTENT_LENGTH = 2 * 1024 * 1024  # 2 MB
